### ISSUE TITLE
npm package ?

### ISSUE THREAD

**Issue by eviltik** [PetrosiliusPatter/ingooutgo#1]
Hi, great job !

Wondering if you think about releasing a version on npm ?

**Comment by PetrosiliusPatter** [comment]
Sorry for the late reply!!

Yes, currently there is no way to install, without cloning and linking it locally 😬
I am in the progress of restructuring the project to use Deno, and then release it on both denoland and npm!
I think I'll manage within this month. Early December, at the latest!  
I'll gladly notify you here. Thanks for the interest!

**Comment by PetrosiliusPatter** [comment]
Well, a bit later than "early December", but there we go! Changed some things, updated some things, added some things, and published all of it to Denoland and NPM!  
Added a new README as well, including install instructions.  
Merry Christmas! 🎄🎄🎄
